### ISSUE TITLE
New Version ZipZap doenst work on Meteor 0.7.2

### ISSUE THREAD

**Issue by e0901026** [udondan/meteor-zipzap#1]
I am using zipzap 0.1.2 in my project, it works fine and when I update to zip upper than 0.2 version. the zip.saveAs function doesnt work any more.
And the browser throw the errors: *Meteor.saveAs is not a function*        
```         
            var zip = new JSZip();
             // Add content to Zip file
             zip.file('textfile.txt', 'Hello World');
            // Save to file on client
            zip.saveAs("filename.zip");
```
